Defer Including rules.tao.GNU for gnuace
DOCGroup/ACE_TAO pull request #1470
Opened 2021-04-08 04:52 UTC by iguessthislldo

Alternative fix for https://github.com/objectcomputing/OpenDDS/pull/2559. See there for details.

https://github.com/DOCGroup/ACE_TAO/pull/1296 changed the order of includes of rules make files to effectively being how the base projects that set them are included. This can lead to the order of `GNUACE_PROJECT_VERSION ?=` being set differently than what the case was in ACE6/TAO2. The result in OpenDDS is that so library files get TAO's version number.

This tires to fix that by including `tao.rules.GNU` at a marker after the `extension` marker.

2021-04-08 07:45 UTC, mcorino requested changes
The new tao_rules was introduced to create correctly (in our opinion) ordered `rules.*` includes where the rules for a "derived" library gets inserted before a "base" library.
In AXCIOMA the manual insertions for CIAO, DAnCE and TAO and non-ordered `rules.*` includes were messing up the versioning schemes for libraries. This seemed like a more logical approach. I agree the issue with `GNUACE_PROJECT_VERSION` is the real underlying problem but did not have a better idea to fix that.

2021-04-08 13:37 UTC, mitza-oci commented
In order to facilitate a smooth migration from TAO 2 to 3 for any downstream project, we should maintain the behavior that
`<%marker(extension)%>` comes before `rules.tao.GNU` is included.
I think it's reasonable (though maybe not what we want long term) for TAO to be handled as a special case since it's in this same repository.

2021-04-08 14:30 UTC, mcorino commented
> In order to facilitate a smooth migration from TAO 2 to 3 for any downstream project, we should maintain the behavior that
> `<%marker(extension)%>` comes before `rules.tao.GNU` is included.

The way things were before #1296 the `rules.tao.GNU` would only be included after the `extension` marker for a project for which the `tao` MPC value would evaluate to `true` which is handled by an obscure and unreliable piece of code in `$ACE_ROOT/bin/MakeProjectCreator/modules/GNUACEProjectCreator.pm` based on comparisons of include and library paths with similar setups for `ciao` and `dance`. Using that setup was a disaster waiting to happen and it did for AXCIOMA.
I can live with a reliable solution for inserting the include of `rules.tao.GNU` after the `extension` marker for any project using tao instead of relying on the correct order of using the current `tao_rules` base project as that should work just fine for AXCIOMA without any changes. The proposed solution does exactly that but I had hoped for a solution without the need for yet again another verbatim section.

2021-04-08 19:25 UTC, mitza-oci approved these changes

2021-04-10 09:34 UTC, mcorino approved these changes

2021-04-12 15:41 UTC, merged