Fix for issue #1550 - empty case evaluation on unions with enum discriminators
DOCGroup/ACE_TAO pull request #1551
Opened 2021-06-14 23:03 UTC by pmesnier

see issue #1550 for detailed description of the issue. 

Briefly, the IDL compiler incorrectly fails to evaluate union branch labels that serve as aliases of default cases.

2021-06-14 23:43 UTC, iguessthislldo requested changes

2021-06-14 23:43 UTC, iguessthislldo commented on TAO/TAO_IDL/ast/ast_union_branch.cpp
> +      }
```suggestion
        {
          continue;
        }
```

2021-06-14 23:43 UTC, iguessthislldo commented on TAO/tests/IDLv4/annotations/annotation_tests.cpp
> +    test_union->field(af,2);
```suggestion
    test_union->field(af, 2);
```

2021-06-14 23:43 UTC, iguessthislldo commented on TAO/tests/IDLv4/annotations/annotation_tests.cpp
> +     t.failed("did not get the correct label value");
```suggestion
      t.failed("did not get the correct label value");
```

2021-06-15 18:13 UTC, iguessthislldo requested changes

2021-06-15 18:13 UTC, iguessthislldo commented on TAO/tests/IDLv4/annotations/annotation_tests.cpp
> +    }
```suggestion
    if (ul->label_val()->ev()->u.ulval != 2)
      {
        t.failed("did not get the correct label value");
      }
```

2021-06-15 18:39 UTC, iguessthislldo approved these changes

2021-06-16 01:41 UTC, merged

2021-06-16 06:22 UTC, jwillemsen commented
@pmesnier Do you also merge these changes to master?

2021-08-02 13:58 UTC, jwillemsen commented
@pmesnier @mitza-oci @iguessthislldo  Is this also fixed on master?

2021-08-02 14:28 UTC, jwillemsen commented
Ok, did now find #1555 as merge of this one on master