[ACE 6] Fixed warnings related to Handle_Set's copy constructor
DOCGroup/ACE_TAO pull request #1641
Opened 2021-08-03 16:05 UTC by mitza-oci

GCC 11:
```
ace/Select_Reactor_T.cpp:1496:18: warning: implicitly-declared 'constexpr ACE_Handle_Set::ACE_Handle_Set(const ACE_Handle_Set&)' is deprecated [-Wdeprecated-copy]
ace/Handle_Set.inl:31:1: note: because 'ACE_Handle_Set' has user-provided 'ACE_Handle_Set& ACE_Handle_Set::operator=(const ACE_Handle_Set&)'
```
Not a problem for ACE 7

2021-08-03 17:00 UTC, jwillemsen commented
See #1463 for the fix on master. Can this be for the next micro, our builds are already running

2021-08-03 17:34 UTC, mitza-oci commented
> 
> 
> See #1463 for the fix on master.

The code I added is equivalent to what the compiler's already doing, member-wise (trivial) copy construction.

> Can this be for the next micro, our builds are already running

Yes, just want to get the last warning off of our GCC 11 build that uses the `ace6tao2` branch with OpenDDS

2021-08-03 17:35 UTC, jwillemsen commented
We should have the same change on master and ace6tao2

2021-08-03 17:56 UTC, mitza-oci commented
> 
> 
> We should have the same change on master and ace6tao2

I don't think anything's going to be faster than a trivial copy, compiler can turn it in to a `memcpy`.  But maybe there's something about how this is used that I'm not aware of.

2021-08-04 08:07 UTC, jwillemsen commented
In terms of long terms maintenance it looks safer to have the same fix as on master backported and not a different change.

2021-08-04 08:08 UTC, jwillemsen requested changes
In terms of long terms maintenance it looks safer to have the same fix as on master backported and not a different change.

2021-08-04 13:25 UTC, mitza-oci commented
> 
> 
> In terms of long terms maintenance it looks safer to have the same fix as on master backported and not a different change.

I think there are tradeoffs for each option.  It may be better to have stability for ACE 6.

I'd be fine with closing this PR and merging some other approach, I'd just like to avoid having ACE headers generate warnings in downstream projects using default compiler options.

2021-08-04 15:15 UTC, jwillemsen commented
Newer compilers just give a lot of warnings, trying to get ace6tao2 warning free will result in much more changes, even master gives several warnings with newer compilers. Personally I am not in favor of trying to get ace6tao2 warning free, would prefer to get master warning free.

2021-08-20 21:13 UTC, mitza-oci commented
> 
> 
> Newer compilers just give a lot of warnings, trying to get ace6tao2 warning free will result in much more changes, even master gives several warnings with newer compilers. Personally I am not in favor of trying to get ace6tao2 warning free, would prefer to get master warning free.

The goal is not to get the build completely warning-free.  The goal is to get warnings out of public headers that are commonly used since they will cause issues for downstream projects.

2021-08-21 07:14 UTC, jwillemsen commented
> > Newer compilers just give a lot of warnings, trying to get ace6tao2 warning free will result in much more changes, even master gives several warnings with newer compilers. Personally I am not in favor of trying to get ace6tao2 warning free, would prefer to get master warning free.
> 
> The goal is not to get the build completely warning-free. The goal is to get warnings out of public headers that are commonly used since they will cause issues for downstream projects.

But most of that work for newer compilers is already done on master, when someone has a new compiler that gives these new warnings why not upgrade to ACE7 which has the fixes? These new compilers already have C++11 or even C++17 as default C++ level so it is not that we are forcing users to do something additionally. Is there a real reason why they have to keep using ACE 6?

2021-09-06 16:22 UTC, mitza-oci commented
I guess this isn't going to be resolved in time for the upcoming release.  That's fine, it can happen later.

In terms of overall approach to ACE 6, if any of the maintainers don't want to work on this branch then that's OK.  Those that do can maintain it.

2021-11-05 20:47 UTC, jrw972 approved these changes

2021-11-10 14:32 UTC, merged