Fix Floating Point Constant Expressions in tao_idl
DOCGroup/ACE_TAO pull request #1715
Opened 2021-11-04 22:13 UTC by iguessthislldo

Fixes #1713 and adds some regression tests for constant expressions. Also tried to do some more cleanup and minor fixes related to #840.

2021-11-04 22:21 UTC, mitza-oci requested changes

2021-11-04 22:21 UTC, mitza-oci commented on TAO/TAO_IDL/ast/ast_expression.cpp
> +    pd_v1->ev()->et : eval_kind_to_expr_type (ek);
```suggestion
    pd_v1->ev ()->et : eval_kind_to_expr_type (ek);
```
at least 1 more of these below

2021-11-04 22:21 UTC, mitza-oci commented on TAO/TAO_IDL/ast/ast_expression.cpp
> +  {
```suggestion
    {
```

2021-11-05 19:04 UTC, jwillemsen commented on TAO/tests/IDL_Test/expressions.idl
> +  const double sub = a - b;
Maybe add long double also?

2021-11-05 19:05 UTC, jwillemsen approved these changes

2021-11-05 20:37 UTC, mitza-oci approved these changes

2021-11-06 00:03 UTC, merged

2021-11-09 07:22 UTC, jwillemsen commented
One new warning, see https://buildlogs.remedy.nl/win_vs2019_opendds_debug/

```
[Details] 470>X:\BUILD\DOC_ROOT\TAO\TAO_IDL\ast\ast_expression.cpp(1835,12): warning C4804: '%': unsafe use of type 'bool' in operation [X:\BUILD\DOC_ROOT\TAO\TAO_IDL\TAO_IDL_FE.vcxproj]
```