For VCPKG linux build
DOCGroup/ACE_TAO pull request #1751
Opened 2022-01-06 23:26 UTC by pierrebizz

Fix for issue https://github.com/DOCGroup/ACE_TAO/issues/1750

2022-01-07 06:59 UTC, jwillemsen commented on TAO/orbsvcs/orbsvcs/TAO_CosProperty_Serv.pc.in
> +Requires: TAO_PortableServer
``` suggestion
Requires: TAO_CosProperty_Skel
```

2022-01-07 07:01 UTC, jwillemsen requested changes

2022-01-07 07:01 UTC, jwillemsen commented on TAO/tao/Monitor/TAO_Monitor.pc.in
> +Requires: TAO_PortableServer, ACE_ETCL_Parser
ACE_MonitorControl should be there, looks a pc.in is missing in https://github.com/DOCGroup/ACE_TAO/tree/master/ACE/ace/Monitor_Control

2022-01-07 22:59 UTC, mitza-oci commented
I have some related changes on this branch: https://github.com/mitza-oci/ACE_TAO/tree/gha-install-pc
If it works in GitHub Actions I'll create a PR which could replace this one.
That should at least make the pkg-config files consistent (`pkg-config --exists` works), if not 100% accurate.

2022-01-10 15:25 UTC, mitza-oci commented
See #1752

2022-01-11 03:20 UTC, closed without merging