support thread naming via pthread_setname_np() if available
DOCGroup/ACE_TAO pull request #1763
Opened 2022-01-15 18:01 UTC by esohns

2022-01-15 18:03 UTC, esohns commented
please only mind commit 8eae9d8. Something went wrong during branching

2022-02-07 09:24 UTC, jwillemsen commented
Please limit this PR to only the change mentioned in the subject, also there is no config file that sets ACE_HAS_PTHREAD_SETNAME_NP, that should be set somewhere?

2022-02-07 19:11 UTC, esohns commented
please re-review

2022-02-07 19:41 UTC, jwillemsen commented
Please check the diff, very likely you changes line endings, the diff should only show your changes

2022-02-07 19:43 UTC, jwillemsen commented
Maybe create a new branch from master and only apply the changes that belong this PR, just redo the change or cherry-pick the original change

2022-02-08 12:31 UTC, jwillemsen requested changes

2022-02-08 12:31 UTC, jwillemsen commented on ACE/ace/OS_NS_Thread.cpp
> +  int name_set = 0;
Can be bool and only needs to be there when ACE_HAS_PTHREAD_SETNAME_NP is defined

2022-02-08 12:31 UTC, jwillemsen commented on ACE/ace/OS_NS_Thread.cpp
> +  if (!name_set && thr_name && *thr_name)
Can the bool not be removed when you only do this code when ACE_HAS_PTHREAD_ATTR_SETNAME is not defined?

2022-02-09 07:45 UTC, merged