added some missing ctor initializers
DOCGroup/ACE_TAO pull request #1764
Opened 2022-01-15 18:04 UTC by esohns

2022-01-15 18:04 UTC, esohns commented
please mind only commit 90cf05a. Something went wrong during branch creation.

2022-02-02 14:03 UTC, jwillemsen commented on ACE/ace/Timer_Heap_T.cpp
> +    iterator_ (NULL),
NULL is not portable, given that we mandate C++11 please use nullptr

2022-02-02 14:03 UTC, jwillemsen commented on ACE/ace/Message_Block.cpp
> +          ACE_NEW_NORETURN (new_message_block,
Please remove this from this PR, this is already part of another one

2022-02-03 08:46 UTC, jwillemsen commented on ACE/ace/Timer_Heap_T.cpp
> +    iterator_ (NULL),
The fuzz build gives an error about this

2022-02-03 08:46 UTC, jwillemsen requested changes
See comments

2022-02-06 20:23 UTC, merged