Debian11 with gcc10
DOCGroup/ACE_TAO pull request #1812
Opened 2022-04-01 22:24 UTC by shuston

Work in progress.

Bringing a customer's changes in to current dev to support Debian 11 w/ gcc10.

2022-04-02 09:59 UTC, jwillemsen commented
Steve, can you do a global search in ACE/TAO for any fallthrough comments and replace that with `ACE_FALLTHROUGH` as part of this PR, I think there are a few more places where we have used that comment to silence a warning.

2022-04-02 16:05 UTC, shuston commented
Hi Johnny,

I will check through ACE, but I am not familiar enough with TAO to get into that.

-Steve

From: Johnny Willemsen ***@***.***>
Sent: Saturday, April 02, 2022 6:00 AM
To: DOCGroup/ACE_TAO ***@***.***>
Cc: Steve Huston ***@***.***>; Author ***@***.***>
Subject: Re: [DOCGroup/ACE_TAO] Debian11 with gcc10 (PR #1812)


Steve, can you do a global search in ACE/TAO for any fallthrough comments and replace that with ACE_FALLTHROUGH as part of this PR, I think there are a few more places where we have used that comment to silence a warning.

—
Reply to this email directly, view it on GitHub<https://github.com/DOCGroup/ACE_TAO/pull/1812#issuecomment-1086605912>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAADBPXSA6WZOLA47XS46MLVDALCRANCNFSM5SJ5VGJA>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

2022-04-04 06:52 UTC, jwillemsen commented
Hi,

> Hi Johnny, I will check through ACE, but I am not familiar enough with TAO to get into that.

Looks a global find/replace will probably work, I will do that on TAO after you have finished and merged this PR

2022-04-04 06:54 UTC, jwillemsen commented on ACE/ace/Name_Proxy.cpp
> +  ssize_t length = ACE_NTOHL (reply.length ());
length as const?

2022-04-04 06:55 UTC, jwillemsen commented on ACE/ace/Time_Value.h
> +  ACE_Time_Value (const ACE_Time_Value &tv);
Why does the default version not work? When there is a use-case where the default doesn't work we should add a test case for that

2022-04-04 06:56 UTC, jwillemsen commented on ACE/ace/Handle_Set.h
> +
Did something change in Handle_Set.h/inl, looking at the diffs it only looks some operations got moved in the file itself?

2022-04-04 06:58 UTC, jwillemsen commented on ACE/ace/Atomic_Op.h
> +  ACE_Atomic_Op<ACE_Thread_Mutex, unsigned long> &operator= (const ACE_Atomic_Op<ACE_Thread_Mutex, unsigned long> &c);
Some test extension for this operation? With C++11 we do prefer std::atomic, we should be careful extending ACE_Atomic_Op, not that we add all kinds of ACE extensions which make it harder later for users to migrate to std::atomic

2022-04-04 14:30 UTC, mitza-oci requested changes

2022-04-08 13:29 UTC, mitza-oci commented on ACE/ace/Handle_Set.inl
> +ACE_Handle_Set::ACE_Handle_Set (const ACE_Handle_Set &rhs)
This is changing the order of the copy constructor and copy assignment operator (see line 43) which makes the diff harder to read.  Is the order significant?

2022-04-08 13:29 UTC, mitza-oci commented on ACE/tests/Naming_Test.cpp
> +                       ACE_OS::getpid ());
Is `pid_t` larger than int on any current (or future?) platform?

2022-04-21 21:03 UTC, merged

2022-04-24 12:44 UTC, jwillemsen commented
@shuston Steve, the `pid_t` related change results in a new warning with mingw64, see https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_137, can you have a look?

```
[[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_137)] x:/BUILD/DOC_ROOT/ACE/tests/Naming_Test.cpp: In function 'int run_main(int, ACE_TCHAR**)':
[[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_138)] x:/BUILD/DOC_ROOT/ACE/tests/Naming_Test.cpp:263:34: warning: format '%d' expects argument of type 'int', but argument 5 has type 'pid_t' {aka 'long long int'} [-Wformat=]
[[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_139)] X:/BUILD/DOC_ROOT/ACE/ace/ace_wchar.h:97:27: note: in definition of macro 'ACE_TEXT'
```

2022-04-25 13:57 UTC, shuston commented
> @shuston Steve, the `pid_t` related change results in a new warning with mingw64, see https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_137, can you have a look?
> 
> ```
> [[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_137)] x:/BUILD/DOC_ROOT/ACE/tests/Naming_Test.cpp: In function 'int run_main(int, ACE_TCHAR**)':
> [[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_138)] x:/BUILD/DOC_ROOT/ACE/tests/Naming_Test.cpp:263:34: warning: format '%d' expects argument of type 'int', but argument 5 has type 'pid_t' {aka 'long long int'} [-Wformat=]
> [[Details](https://buildlogs.remedy.nl/win_mingw64_64_tao/2022_04_24_07_04_Full.html#warning_139)] X:/BUILD/DOC_ROOT/ACE/ace/ace_wchar.h:97:27: note: in definition of macro 'ACE_TEXT'
> ```

Absolutely... apologies for that error, Johnny. @mitza-oci - you tried to warn me - sorry, I misunderstood what you were saying.